### ISSUE TITLE
Create "Meet the team" page

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/website#30]
Core team: please add a few sentences about you in a comment which we can then compile for a new "meet the team" page. Thanks!

**Comment by johnspackman** [comment]
John Spackman is a life-long software developer, starting in C and C++ before ending up in Java and Javascript, with a brief diversion into Delphi.  John builds software systems for corporates, sometimes managing large quantities of data and code - John's company, Zenesis Ltd, actively maintains around a million lines of code in production systems.  On his days off, John enjoys rebuilding rotary engines and working on his small holding with his extended family of 4 generations, dogs, cats, sheep, pigs, geese, turkeys...and a horse.

**Comment by cboulanger** [comment]
Berlin-based social scientist, part-time coder, and open source enthusiast (JavaScript/NodeJS/PHP). Developer of http://bibliograph.org. For my coding activities, see [GitHub](https://github.com/cboulanger)  and [Twitter](https://twitter.com/herr_panyasan). My academic persona can be found here: [University](https://www.lehrstuhl-moellers.de/mitarbeiterinnen/dr-christian-boulanger) | [Twitter](https://twitter.com/cmboulanger) | [Publications](https://hu-berlin.academia.edu/ChristianBoulanger).

**Comment by oetiker** [comment]
Tobi Oetiker has a degree in Electrical Engineering from the ETH in Zurich. He published hist first OpenSource software package in 1994. A network monitoring script named MRTG which became quite popular back in the day. Tobi lives in Switzerland and co-owns a small software and sysadmin company. His favorite programming Languages are Perl and JavaScript and he is still looking for an excuse todo a project in Rust.

**Comment by zaucker** [comment]
After getting a degree in physics and chemistry, Fritz Zaucker spent some years in New York working on a PhD in environmental physics which he received from the University of Heidelberg, Germany. After a couple of years working in climate change research he returned to Europe and led the IT support group of the Department of Electrical Engineering and Information Technology at ETH Zurich. Occasionally Fritz is teaching introductionary courses internet technologies and  databases and since 2007 is managing director of [OETIKER+PARTNER AG](https://www.oetiker.ch), Olten, Switzerland.

**Comment by hkollmann** [comment]
Henner Kollmann has a degree in Electrical Engineering from the RWTH in Aachen. He is working for [aucos Ag](https://www.aucos.de/) as senior software developer with Delphi, Java, Javascript, C++, Qt and SQL. In his freetime he supports since 2010 the developing of [VZAweb: web-based traffic census data base](https://www.vzaweb.de/) which is fully based on qooxdoo.

**Comment by derrell** [comment]
Derrell Lipman has been working at the cutting edge of, and innovating in the computer science arena for 40+ years, including porting Unix Version 7 to the PDP-11, and inventing windows before Bill and friends. He has been an active contributor to qooxdoo for about 15 years. Derrell has a BS in Computer Science from University of the Pacific, and masters and Ph.D. from University of Massachusets, Lowell. Professionally, Derrell currently holds the title of Principal Innovation Architect.  Derrell enjoys spending time with his family, playing racquetball and ping pong, running around with and training his puppy, and is a mentor for the local high school's FIRST (FRC) robotics team.

**Comment by cboulanger** [comment]
Done with 20b4e1f1f9da3bec24c9606f28bc5ca9147f508c.
